version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
           - "80:80"
        volumes:
           - /var/run/docker.sock:/tmp/docker.sock:ro

    emby:
        image: emby/embyserver
        container_name: emby
        # net: host
        ports:
            - 8096:8096
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - $HOME/.config/embyserver:/config
            - /media/My Passport/peliculas:/media
        environment:
            - VIRTUAL_PORT=8096
            - VIRTUAL_HOST=emby.htpc
            - AUTO_UPDATES_ON=true
            - APP_UID=1000
            - APP_GID=1000

    mrpotato:
        image: rolfkoenders/potato
        container_name: mrpotato
        restart: always
        links:
            - couchpotato
        env_file: $HOME/.config/mrpotato/env

    dashboard:
        image: chimpchimp/manage-this-node
        container_name: dashboard
        ports:
            - 3000:3000
        volumes:
            - $HOME/.config/dashboard:/config
        restart: always
        environment:
            - VIRTUAL_HOST=dashboard.htpc
            - PGID=1000
            - PUID=1000

    couchpotato:
        image: linuxserver/couchpotato
        container_name: couchpotato
        # network_mode: "host"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - $HOME/.config/couchpotato:/config
            - $HOME/Downloads/torrents/completed/Movies:/downloads
            - /media/My Passport/peliculas:/movies
        ports:
            - 5050:5050
        links:
            - plex
            - utorrent
        restart: always
        environment:
            - VIRTUAL_HOST=couchpotato.htpc
            - PGID=1000
            - PUID=1000

    plex:
        image: linuxserver/plex
        container_name: plex
        # network_mode: "host"
        ports:
            - 32400:32400
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - $HOME/.config/plexmediaserver:/config
            - /media/My Passport/peliculas:/data/movies
        restart: always
        environment:
            - VIRTUAL_PORT=32400
            - VIRTUAL_HOST=plex.htpc
            - VERSION=latest
            - PGID=1000
            - PUID=1000

    utorrent:
        image: ekho/utorrent
        container_name: utorrent
        network_mode: "host"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - $HOME/Downloads:/data
            - $HOME/.config/utorrent:/utorrent
        ports:
            - 8080:8080
            - 6881:6881
        restart: always
        environment:
            - VIRTUAL_PORT=8080
            - VIRTUAL_HOST=utorrent.htpc

    hamachi:
        image: gfjardim/hamachi
        container_name: hamachi
        network_mode: "host"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - $HOME/.config/hamachi:/config
        restart: always
        environment:
            - ACCOUNT="myemail@gmail.com"
        privileged: true
